POST http://localhost:8080/api/user/register HTTP/1.1
content-type: application/json

{
    "username": "hieuhoangbt",
    "email": "trunghieu186@gmail.com",
    "password": "password",
    "phone": "+84368306484"
}
